apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotel-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hotel-api
  template:
    metadata:
      labels:
        app: hotel-api
    spec:
      containers:
        - name: hotel-api-container
          image: docker.io/ndeta100/hotel-api:latest
          ports:
            - containerPort: 3000
          env:
            - name: MONGO_DB_URL
              valueFrom:
                secretKeyRef:
                  name: hotel-api-secrets
                  key: MONGO_DB_URL
            - name: MONGO_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: hotel-api-secrets
                  key: MONGO_DB_NAME
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: hotel-api-secrets
                  key: JWT_SECRET
            - name: HTTP_LISTEN_ADDRESS
              valueFrom:
                 secretKeyRef:
                  name: hotel-api-secrets
                  key: HTTP_LISTEN_ADDRESS
            - name: MONGO_DB_URL_TEST
              valueFrom:
                secretKeyRef:
                  name: hotel-api-secrets
                  key: MONGO_DB_URL_TEST