apiVersion: v1
kind: Service
metadata:
  name: hotel-api-service
  namespace: hotel-api
spec:
  selector:
    app: hotel-api
  ports:
    - protocol: TCP
      port: 3000 # The port through which your application will be exposed externally
      targetPort: 3000 # The port your Spring Boot application listens on inside the container
  type: LoadBalancer