apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv
spec:
  storageClassName: gp2
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/kubernetes-storage/mongodb
  nodeAffinity:
    nodeSelectorTerms:
      - matchExpressions:
        - key: "kubernetes.io/os"
          operator: In
          values:
            - linux

