apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv
  namespace: mongodb
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: mongodb-storageclass
  local:
    path: /mnt/kubernetes-storage/mongodb
  nodeSelector:
    size: large















# apiVersion: v1
# kind: PersistentVolume
# metadata:
#     name: mongodb-pv
#     namespace: mongodb
# spec:
#   capacity:
#     storage: 2Gi
#   volumeMode: Filesystem
#   accessModes:
#     - ReadWriteOnce
#   persistentVolumeReclaimPolicy: Retain
#   storageClassName: mongodb-storageclass
#   local:
#     path: /mnt/kubernetes-storage/mongodb
#   nodeAffinity:
#     required:
#       nodeSelectorTerms:
#       - matchExpressions:
#         - key: size
#           operator: In
#           values:
#             - large