---
apiVersion: v1
kind: Service
metadata:
  name: portainer
  namespace: portainer
spec:
  type: NodePort
  ports:
    - name: web
      port: 9000
      targetPort: 9000
      nodePort: 30777
      protocol: TCP
    - name: agent
      port: 8000
      targetPort: 8000
      nodePort: 30778
      protocol: TCP
  selector:
    app: portainer