apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: portainer-storageclass-rolebinding
subjects:
- kind: ServiceAccount
  name: default
  namespace: portainer
roleRef:
  kind: ClusterRole
  name: portainer-storageclass-role
  apiGroup: rbac.authorization.k8s.io
